apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2023-11-09T07:08:13Z"
  generation: 3
  labels:
    app: test-deploy
  name: test-deploy
  namespace: test-ns 
  resourceVersion: "289339"
  uid: caaccad0-46e8-4a06-9256-085def221c06
spec:
  progressDeadlineSeconds: 600
  replicas: 7
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test-deploy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-deploy
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpass
        - name: MYSQL_USER
          value: user
        - name: MYSQL_PASSWORD
          value: pass
        - name: MYSQL_DATABASE
          value: testdb
        image: registry.ocp4.example.com:8443/rhel8/mysql-80
        imagePullPolicy: Always
        name: mysql-80
        ports:
        - containerPort: 3306
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: test-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: test-volume
        persistentVolumeClaim:
          claimName: test-pvc
status:
  availableReplicas: 7
  conditions:
  - lastTransitionTime: "2023-11-09T07:08:13Z"
    lastUpdateTime: "2023-11-09T07:11:41Z"
    message: ReplicaSet "test-deploy-cfc6f87bf" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-11-09T07:12:53Z"
    lastUpdateTime: "2023-11-09T07:12:53Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 7
  replicas: 7
  updatedReplicas: 7
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: test-pvc
  namespace: test-ns
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
